### ISSUE TITLE
README not updated to reflect removal of examples

### ISSUE THREAD

**Issue by protoz** [instana/go-sensor#117]
This was my first time trying to get started with go-sensor and multiple links in the README point to paths that no longer exist:

https://github.com/instana/go-sensor/blob/master/example/httpclient/
https://github.com/instana/go-sensor/blob/master/example/webserver/

You have to navigate to the readme of example to find where you should look for up to date examples.   This should be in the main README to improve the readability of documentation.

**Comment by andrewslotin** [comment]
Hey @protoz, thanks for filing this issue! These links in README are indeed outdated. We recently started moving the code examples to godoc to make sure they are up-to-date with the code changes. I'm going to update the README to make it more explicit and for now please check the [`"Overview" section`](https://pkg.go.dev/github.com/instana/go-sensor?tab=doc#pkg-overview) of `go-sensor` documentation to see an example of `http.Client` and `http.Handler` instrumentation. Let me know if this helps.
