### ISSUE TITLE
Needed: A better logging strategy

### ISSUE THREAD

**Issue by pglombardo** [instana/go-sensor#13]
Pointed out by @monolovl in #2 the logging could be improved in this package.

To be consistent with our other languages we need a logger that:

1. Supports Debug/Warn/Info/Fatal levels
2. Configurable in-code & replaceable by app logger
3. Configurable via environment variables
4. Defaults to stdout/stderr but configurable
5. Messages prefixed with `[instana]` or equivalent

General goal for instrumentation is to:

1. Boot a single boot message and not print anything else if all goes well
2. In case of error, print a _single_ error and handle in best case
3. If handling is not possible, deactivate the sensor and sit in a corner

**Comment by mier85** [comment]
the instana prefix shouldn't be hardcoded. We use structured logging, so we would add a field to the logger that says "lib":"instana" or something like that instead of having it inside the log message itself
