### ISSUE TITLE
[Bug]: sql: converting argument $2 type: unsupported type sql.Out, a struct when instrumenting Db2

### ISSUE THREAD

**Issue by maxatcn** [instana/go-sensor#343]
### Problem Description

When enabling Instana monitor on Dd2 , there is error return when calling Store Procedure with OUT parameter, for example,
```
_, dbErr := db.Exec(sqlString, sql.Out{Dest: &returnValue})
```
It does work when disabling Instana and there is no error returned.

The instrument done as follwing,
```
// Create a new instana.Sensor instance
sensor := instana.NewSensor("dv-api-instana-db")

// Create an instance of *sql.DB to use for database queries
db, err := instana.SQLInstrumentAndOpen(sensor, "go_ibm_db", con)
```

### Go Version

go.1.19, go 1.18.5

### go.mod

```shell
github.com/ibmdb/go_ibm_db v0.4.1
github.com/instana/go-sensor v1.43.4
```

### go env

```shell
N/A
```

**Comment by maxatcn** [comment]
@willianpc , can you please help take a look?  Thanks.

**Comment by willianpc** [comment]
Hi @maxatcn thanks for reporting the issue.
We will take a look and come back to you ASAP.

_ Willian

**Comment by willianpc** [comment]
Hi @maxatcn ,
I am trying to reproduce the issue, but it seems to be working for me.
Could you maybe provide a full example (omitting sensitive data, of course)?

If you could provide us with the full code snippet of the working and broken code, it would be even perfect.

Best,
_ Willian

**Comment by willianpc** [comment]
One more thing, @maxatcn : can you also provide the error you are receiving?

Best,
_ Willian

**Comment by maxatcn** [comment]
@willianpc ,  sorry, the error message is in the title, `sql: converting argument $2 type: unsupported type sql.Out, a struct`,  here $2 is the parameter position for the OUT parameter.

For example,
```
var diags string

	stringArray := []string{"call ", SchemaName, ".XXXTABLEV3(?,?,?,?);"}
	queryString := BuildSQLQuery(stringArray)

	st, err := db.Prepare(queryString)
	if err != nil {
		log.Println(queryString)
		log.Println(err.Error())
		return nil, NewDvError(errors.New(diags), 500, diags)
	}

	rows, err := st.Query(tName, sList, optionsCSV, sql.Out{Dest: &diags})

	if rows == nil {
		log.Error(queryString)
		log.Println(diags)
		log.Error(err.Error())
		return nil, NewDvError(errors.New(diags), 500, diags)
	}

	defer rows.Close()

```

For SP XXXTABLEV3(?,?,?,?),  the first 3 are IN parameters, the 4nd is OUT parameter.

The issue only happens when calling SP(Store Procedure) with OUT parameter.  The SELECT query works fine.

**Comment by willianpc** [comment]
Thanks, @maxatcn , I am able to reproduce the issue now.
I come back to you as soon as I have any updates :)

_ Willian

**Comment by willianpc** [comment]
Hi @maxatcn we released a [new version](https://pkg.go.dev/github.com/instana/go-sensor@v1.45.0) of the tracer that introduces the instrumentation of sql.Out and now it should work fine for you.

Could you update the tracer to the [v1.45.0](https://pkg.go.dev/github.com/instana/go-sensor@v1.45.0) and check again?

Also, let us know the results, so we can close the issue.

Best,
_ Willian

**Comment by maxatcn** [comment]
Great. Thanks for the effort @willianpc .   I will try later once back from the public holidays.

**Comment by maxatcn** [comment]
Sorry for the late reply @willianpc .   Just got the code change deployed and tested today.   As far as I can see, all the SP calls work properly.  I will keep test and monitor.   Let's close this issue for now.  Thank you for you great support!
