### ISSUE TITLE
instaredis is not compatible with go-redis/v9

### ISSUE THREAD

**Issue by guli-nl** [instana/go-sensor#390]
### Problem Description

instaredis documentation states that it is compatible with [go-redis client](https://github.com/redis/go-redis), however upon initialization, I get the following type mismatch error:

<img width="747" alt="Screenshot 2023-01-26 at 3 32 03 PM" src="https://user-images.githubusercontent.com/100302725/214974514-70f1434c-9014-4f93-ac93-99e3a58cfdb2.png">

Since we're using Redis 7, we cannot use v8 for go-redis.

### Minimal, Complete, Verifiable, Example

Below snippet won't build as the client passed in doesn't match the expected interface

```
import (
         instana "github.com/instana/go-sensor"
	"github.com/instana/go-sensor/instrumentation/instaredis"
	"github.com/redis/go-redis/v9"
)

func main() {
 sensor := instana.NewSensor("test-app-tracing") 
 client := redis.NewClient(&redis.Options{
			Addr:     "localhost:6379",
			Password: "12345",
			DB:       0,
		})
      )
 instaredis.WrapClient(client, sensor)
}
```

### Go Version

1.19

### go.mod

```shell
github.com/instana/go-sensor/instrumentation/instaredis v1.4.0
	github.com/redis/go-redis/v9 v9.0.0-rc.4
	github.com/instana/go-sensor v1.49.0


	github.com/go-redis/redis/v8 v8.11.4 // indirect
```

### go env

```shell
N/A
```

**Comment by willianpc** [comment]
Hi @guli-nl thanks for the report.
I will include the instrumentation of redis v9 in our backlog and come back to you once we have updates on it.

BR,
_ Willian

**Comment by sanojsubran** [comment]
Hi @guli-nl ,
We have released a new major version of [instaredis](https://github.com/instana/go-sensor/releases/tag/instrumentation%2Finstaredis%2Fv2.0.0) for the go-redis v9 support. Kindly check it. The go pkg reference can be found [here](https://pkg.go.dev/github.com/instana/go-sensor/instrumentation/instaredis/v2).

**Comment by guli-nl** [comment]
@sanojsubran thank you so very much! This was very quick, me and my team appreciate it :)

**Comment by sanojsubran** [comment]
@guli-nl Welcome! Kindly close the issue if it is resolved.

**Comment by sanojsubran** [comment]
Closing the issue as resolved.
