### ISSUE TITLE
Shopify has transferred the ownership of sarama to IBM

### ISSUE THREAD

**Issue by VipulZopSmart** [instana/go-sensor#447]
### Problem Description

Hi team,

We used to use this https://pkg.go.dev/github.com/instana/go-sensor/instrumentation/instasarama for the instana integration with our code, but now as the ownership has been changed for the sarama, how much time will we be able to get the updated one?
https://github.com/IBM/sarama
Any idea? Any thoughts?

### Go Version

go1.19

### go.mod

```shell
.
```

### go env

```shell
.
```

**Comment by sanojsubran** [comment]
Thanks @VipulZopSmart for reporting the issue. We are planning to provide a release based on the latest version of sarama. We'll update this ticket once it is done.

**Comment by sanojsubran** [comment]
Hi @VipulZopSmart ,
We have released a new version on instasarama v1.16.0 with the relevant changes. Kindly check it [here](https://pkg.go.dev/github.com/instana/go-sensor/instrumentation/instasarama@v1.16.0).
