### ISSUE TITLE
Update instaamqp to use github.com/rabbitmq/amqp091-go

### ISSUE THREAD

**Issue by wjason94ibm** [instana/go-sensor#459]
### Problem Description

In your GitHub repo https://github.com/instana/go-sensor/blob/main/instrumentation/instaamqp/go.mod , for amqp, you are using deprecated pkg `github.com/streadway/amqp`. The new package is https://github.com/rabbitmq/amqp091-go. Can you please update the repo to use this new Go pkg?

### Go Version

.

### go.mod

```shell
.
```

### go env

```shell
.
```

**Comment by wjason94ibm** [comment]
Did not see that you also have https://github.com/instana/go-sensor/tree/main/instrumentation/instaamqp091.
There should be a big notice in https://github.com/instana/go-sensor/blob/main/instrumentation/instaamqp that indicates it is deprecated or not maintained

**Comment by willianpc** [comment]
> Did not see that you also have https://github.com/instana/go-sensor/tree/main/instrumentation/instaamqp091. There should be a big notice in https://github.com/instana/go-sensor/blob/main/instrumentation/instaamqp that indicates it is deprecated or not maintained

We do still maintain the old version even though it is deprecated/archived, but adding a notice is a good idea and we will work on it.

Thanks for the feedback!
