### ISSUE TITLE
User cannot write their own Recorder

### ISSUE THREAD

**Issue by etsangsplk** [instana/go-sensor#55]
It provided a public interface but accepts parameter only visible within instana.

Recorder is usspoed to be user configurable setting:
https://github.com/instana/go-sensor/blob/493edb42228321483dd4d59ade71ca93fa89d66b/tracer.go#L113

Recorder is accepting *spanS which end user cannot use because it is private.
https://github.com/instana/go-sensor/blob/493edb42228321483dd4d59ade71ca93fa89d66b/recorder.go#L13

**Comment by CodingFabian** [comment]
Thanks for your contribution. This certainly can be improved, but I am curious why you would want your own recorder. Can you pleasee give a bit of background on the use case so we can support it better?

**Comment by pglombardo** [comment]
We're not going to support user configurable recorders for the foreseeable future.  If there are any concerns or requests about this, please let us know [here](https://support.instana.com/hc/en-us/requests/new).
