### ISSUE TITLE
user configurable settings shouldSample and MaxLogPerSpan but are both hardcoded

### ISSUE THREAD

**Issue by etsangsplk** [instana/go-sensor#57]
Looks like they are user ocnfigurable settings but they are both hardcoded
https://github.com/instana/go-sensor/blob/493edb42228321483dd4d59ade71ca93fa89d66b/tracer.go#L113

**Comment by pglombardo** [comment]
These are hard-coded based on Instana's tracing strategy which differs from other OpenTracing tracers.  When using the Instana tracer, configuring these options aren't necessary for the instana dashboard.  Closing this issue but if you wish to follow up, feel free to post any questions [here](https://support.instana.com/hc/en-us/requests/new).
