### ISSUE TITLE
Initialize Tracer with common tags ...

### ISSUE THREAD

**Issue by etsangsplk** [instana/go-sensor#58]
If I want to to tag all the spans with static metadata of microservice (e.g. hostname or other logical naming things) , it will be very helpful if  I can just set that at tracer initialization time, rather than send that on every span as tag.

**Comment by pglombardo** [comment]
See the `Service` option at Tracer initialisation here: https://github.com/instana/go-sensor#opentracing

I'm going to close but let me know if this wasn't what you're looking for.

**Comment by etsangsplk** [comment]
@pglombardo I was referring to static metadata, not just SERVICE.

**Comment by pglombardo** [comment]
Ah makes sense.  Could you [file a support ticket](https://support.instana.com/hc/en-us/requests/new) with your Instana account info?  Then we can look to potentially getting this (and the recorder request) into the pipeline sooner than later.
