### ISSUE TITLE
Go modules support

### ISSUE THREAD

**Issue by toqueteos** [instana/go-sensor#59]
Go modules expects tags to be in `vX.Y.Z` format. Currently they are in `X.Y.Z` format, lacking the first `v`.
It's a one character change and you get `go mod` support for free.

**Comment by pglombardo** [comment]
Thanks @toqueteos for the tip & reminder.  We'll likely do this on the next release.

**Comment by pglombardo** [comment]
Latest version is out with the new tagging schema.  Thanks for the heads up @toqueteos
