### ISSUE TITLE
Opencensus trace exporter

### ISSUE THREAD

**Issue by sylr** [instana/go-sensor#72]
I've written an app https://github.com/sylr/prometheus-azure-exporter which uses the https://github.com/Azure/azure-sdk-for-go library.

azure-sdk-for-go uses the [opencensus library](https://github.com/Azure/azure-sdk-for-go#tracing-and-metrics) so I was wondering if you could implement an opencensus trace exporter for instana.

**Comment by pglombardo** [comment]
Hi @sylr - thanks for filing the issue and letting us know.  I've filed this as a feature request internally for tracking & prioritization.  I'll update here once this progresses.

**Comment by sylr** [comment]
Hi @pglombardo, any updates ?

**Comment by pglombardo** [comment]
Hi @sylr - no updates from my side and considering that OpenTracing and OpenCensus is merging into OpenTelemetry currently I'm not what dynamics that will bring (yet).

For better input, you could talk with the product team directly by filing a ticket [here](https://support.instana.com/hc/en-us/requests/new).  They are the authoritative source for new features.

**Comment by pglombardo** [comment]
Closing - please file a ticket at the link above to get the FR into the pipeline.
