### ISSUE TITLE
[Bug]: instaredis/v2 broken

### ISSUE THREAD

**Issue by vtolstov** [instana/go-sensor#965]
### Problem Description

func (h commandCaptureHook) ProcessHook(next redis.ProcessHook) redis.ProcessHook {
	return func(ctx context.Context, cmd redis.Cmder) error {
		h.handleHook(ctx, cmd, []redis.Cmder{})
		err := next(ctx, cmd)
		return err
	}
}

in this code span started and finished in handleHook before actual redis command handled 
in 	err := next(ctx, cmd)

when you want to fix this ugly case?
span must be started before next called and finished after next returned!

### Go Version

go1.23.

### go.mod

```shell
github.com/redis/go-redis/extra/rediscmd/v9 v9.7.0
	github.com/redis/go-redis/v9 v9.7.0
	github.com/instana/go-sensor/instrumentation/instaredis/v2 v2.15.0 // indirect
```

### go env

```shell
vtolstov@msk-1659tk customer-grpc % go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/vtolstov/Library/Caches/go-build'
GOENV='/Users/vtolstov/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE='bitbucket.sberbank.kz'
GOMODCACHE='/Users/vtolstov/go/pkg/mod'
GOOS='darwin'
GOPATH='/Users/vtolstov/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.23.3/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.23.3/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.23.3'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/vtolstov/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOARM64='v8.0'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='xxxx
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/ym/j5bjj8cn1kn5gmyh6vrdqs580000gn/T/go-build3100268058=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

**Comment by vtolstov** [comment]
if you don't know how to fix, please check https://github.com/redis/go-redis/blob/master/extra/redisotel/tracing.go#L106

**Comment by nithinputhenveettil** [comment]
@vtolstov Thank you for your report. We will look into the issue and get back to you shortly.

**Comment by nithinputhenveettil** [comment]
@vtolstov: I was able to reproduce the issue in the local and am currently working on a fix. I will notify you here once the fixed version is released. Thank you.

**Comment by nithinputhenveettil** [comment]
@vtolstov : We are pleased to inform you that [instaredis v2.15.1](https://github.com/instana/go-sensor/releases/tag/instrumentation%2Finstaredis%2Fv2.15.1) has been successfully released with a fix for this issue.

I'm closing this issue as resolved. However, please feel free to reopen it if you face any problems with this version. 

Thank you very much for your support.
